// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Ud8QzsilzKBagks3j-Xav5UZ1w2vXYU',
    appId: '1:1001493968935:web:fc6edb11ae1571fb79b602',
    messagingSenderId: '1001493968935',
    projectId: 'todoapp-f20eb',
    authDomain: 'todoapp-f20eb.firebaseapp.com',
    storageBucket: 'todoapp-f20eb.appspot.com',
    measurementId: 'G-7W40H32WXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRmSiTTWp97HX01MgO88Wc-nK8SlwvAO4',
    appId: '1:1001493968935:android:1dd09b0b955263bb79b602',
    messagingSenderId: '1001493968935',
    projectId: 'todoapp-f20eb',
    storageBucket: 'todoapp-f20eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhZcWscz-YrttOncSV6KjTn3tobWEq3nE',
    appId: '1:1001493968935:ios:69737ad1827d16c679b602',
    messagingSenderId: '1001493968935',
    projectId: 'todoapp-f20eb',
    storageBucket: 'todoapp-f20eb.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhZcWscz-YrttOncSV6KjTn3tobWEq3nE',
    appId: '1:1001493968935:ios:64a35d383c0cde4079b602',
    messagingSenderId: '1001493968935',
    projectId: 'todoapp-f20eb',
    storageBucket: 'todoapp-f20eb.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
